GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ACCOUNTADMIN;
GRANT USAGE ON DATABASE AIRBYTE TO ROLE ACCOUNTADMIN;
GRANT CREATE SCHEMA ON DATABASE AIRBYTE TO ROLE ACCOUNTADMIN;
GRANT USAGE, CREATE TABLE ON SCHEMA AIRBYTE.BRONZE TO ROLE ACCOUNTADMIN;