acmemart:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: ym82717.snowflakecomputing.com
      user: darorote
      password: your_password  # or use private_key_path for key-pair auth
      role: ACCOUNTADMIN
      database: AIRBYTE
      warehouse: COMPUTE_WH
      schema: BRONZE
      threads: 1